import { Inter } from 'next/font/google'
import './globals.css'
import Navber from '@/components/shared/Navber'
import { Toaster } from 'react-hot-toast'
import Authprovider from '@/components/Authentication/Authprovider'
import Progressber from '@/components/shared/Progressber'




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Food App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={inter.className}>
       <Progressber>
       <Authprovider>
       <Toaster/>
       <Navber></Navber>
        {children}
       </Authprovider>
       </Progressber>
        </body>
    </html>
  )
}
